import type { Metadata } from "next";
import { Anton } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const anton = Anton({
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-anton",
  display: "swap",
})
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${anton.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
